# Generated by Django 4.2.5 on 2023-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_variation'),
        ('orders', '0002_alter_order_payment_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='color',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('New', 'New')], default='New', max_length=50),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='shop.variation'),
        ),
    ]
